indent-width = 4
line-length = 88
target-version = "py38"
cache-dir = "~/.cache/ruff"
fix=true
unsafe-fixes=true

[format]
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = true
line-ending = "auto"

[lint]
select = ["E4", "E7", "E9", "W", "F", "I"]

[lint.isort]
length-sort = true
